apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "54 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob01-container
            image: localhost:32000/cronjob01
            env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: host
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: db
            command: ["/bin/bash","/dbbackup.sh"]
            args:
            - "$(MYSQL_USER)"
            - "$(MYSQL_PASSWORD)"
            - "$(MYSQL_HOST)"
            - "$(MYSQL_DB)"
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pv-claim
